## ----------------------------------------------------------------------------
## ..:: Prometheus POD / Deployment ::..
##-----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: udf-services
  labels:
    app: prometheus
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      version: v1
  template:
    metadata:
      labels:
        app: prometheus
        version: v1
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - env:
        image: prom/prometheus
        imagePullPolicy: IfNotPresent
        name: prometheus
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: prometheus-persistent-storage
          mountPath: /etc/prometheus/prometheus.yml
          subPath: config/prometheus.yml
        - name: prometheus-persistent-storage
          mountPath: /prometheus
          subPath: data
      volumes:
        - name: prometheus-persistent-storage
          hostPath:
            path: /home/ubuntu/dockerhost-storage/prometheus
---
## ----------------------------------------------------------------------------
## ..:: Prometheus POD / Service Configuration ::..
##-----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: prometheus-9090
  namespace: udf-services
  labels:
    app: prometheus
    cis.f5.com/as3-tenant: udf-services
    cis.f5.com/as3-app: prometheus-k3s
    cis.f5.com/as3-pool: prometheus-pool-9090
spec:
  type: ClusterIP
  ports:
  - name: prometheus-http-9090
    port: 9090
    protocol: TCP
  selector:
      app: prometheus