## ----------------------------------------------------------------------------
## ..:: ELK POD / Deployment ::..
##-----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk
  namespace: udf-services
  labels:
    app: elk
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elk
      version: v1
  template:
    metadata:
      labels:
        app: elk
        version: v1
    spec:
      containers:
      - env:
        image: sebp/elk:761
        imagePullPolicy: IfNotPresent
        name: elk
        ports:
        - containerPort: 9200
          protocol: TCP
        - containerPort: 5601
          protocol: TCP
        - containerPort: 5144
          protocol: TCP
        volumeMounts:
        - name: elk-persistent-storage
          mountPath: /etc/logstash/conf.d
          subPath: logstash/conf.d
        - name: elk-persistent-storage
          mountPath: /var/lib/elasticsearch
          subPath: elasticsearch
      volumes:
        - name: elk-persistent-storage
          hostPath:
            path: /home/ubuntu/dockerhost-storage/elk
---
## ----------------------------------------------------------------------------
## ..:: ELK Service Configuration ::..
##-----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: elk-9200
  namespace: udf-services
  labels:
    app: prometheus
    cis.f5.com/as3-tenant: udf-services
    cis.f5.com/as3-app: elk
    cis.f5.com/as3-pool: elk-pool-9200
spec:
  type: ClusterIP
  ports:
  - name: elk-tcp-9200
    port: 9200
    protocol: TCP
  selector:
      app: elk
---
apiVersion: v1
kind: Service
metadata:
  name: elk-5601
  namespace: udf-services
  labels:
    app: prometheus
    cis.f5.com/as3-tenant: udf-services
    cis.f5.com/as3-app: elk
    cis.f5.com/as3-pool: elk-pool-5601
spec:
  type: ClusterIP
  ports:
  - name: elk-tcp-5601
    port: 5601
    protocol: TCP
  selector:
      app: elk
---
apiVersion: v1
kind: Service
metadata:
  name: elk-5144
  namespace: udf-services
  labels:
    app: prometheus
    cis.f5.com/as3-tenant: udf-services
    cis.f5.com/as3-app: elk
    cis.f5.com/as3-pool: elk-pool-5144
spec:
  type: ClusterIP
  ports:
  - name: elk-tcp-5144
    port: 5144
    protocol: TCP
  selector:
      app: elk